export const company = {
  name: "Alfa Technologies",
  legalName: "Alfa Technologies Inc.",
  tagline: "30 Years of Powering IT Infrastructure Across Hyderabad & Secunderabad",
  shortTagline: "Enterprise IT hardware, networking & support since 1996",
  contactPerson: "Jayanth Kunde",
  ownerTitle: "Founder & Proprietor",
  phone: "+91 9246152636",
  phoneHref: "tel:+919246152636",
  phoneDisplay: "+91 92461 52636",
  email: "jaikunde@yahoo.co.uk",
  emailHref: "mailto:jaikunde@yahoo.co.uk",
  city: "Hyderabad",
  region: "Telangana",
  country: "India",
  serviceArea: "Hyderabad & Secunderabad",
  freeDelivery: "Free Door Delivery Anywhere in Hyderabad & Secunderabad",
  ctaHeadline: "Ready to Onboard? Connect With Us Today",
  ctaSubline:
    "Talk to our team about hardware, networking, or an AMC plan built around your uptime needs.",
  yearsExperience: 30,
  slaHours: 3,
  clientCount: 38,
  clientCountLabel: "35+",
  verticalCount: 8,
  siteUrl: "https://alfatechnologiesinc.in",
} as const;
